# Generated by Django 5.1.6 on 2025-06-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
